# Generated by Django 4.2.21 on 2025-05-19 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0002_alter_menuitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('items', models.ManyToManyField(to='LittlelemonAPI.menuitem')),
            ],
        ),
    ]
